// Generated by `opennextjs-cloudflare build` before preview or deployment.
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore The generated module does not exist before the first Cloudflare build.
import handler from "./.open-next/worker.js";
import { runBriefingSchedule } from "./lib/briefing-workflow";

export default {
  fetch: handler.fetch,
  async scheduled(controller: ScheduledController, env: Cloudflare.Env) {
    const now = new Date(controller.scheduledTime);
    const results = await runBriefingSchedule(env, now);
    console.log(JSON.stringify({ event: "briefing_schedule_complete", at: now.toISOString(), results }));
  },
} satisfies ExportedHandler<Cloudflare.Env>;
